using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Game1
{
    class StringHandling
    {
        string[] words = new string[] {
            "ball",
                "bat",
                "bed",
                "book",
                "boy",
                "bun",
                "can",
                "cake",
                "cap",
                "car",
                "cat",
                "cow",
                "cub",
                "cup",
                "dad",
                "day",
                "dog",
                "doll",
                "dust",
                "fan",
                "feet",
                "girl",
                "gun",
                "hall",
                "hat",
                "hen",
                "jar",
                "kite",
                "man",
                "map",
                "men",
                "mom",
                "pan",
                "pet",
                "pie",
                "pig",
                "pot",
                "rat",
                "son",
                "sun",
                "toe",
                "tub",
                "van",
                "apple",
                "arm",
                "banana",
                "bike",
                "bird",
                "book",
                "chin",
                "clam",
                "class   ",
                "clover",
                "club",
                "corn",
                "crayon",
                "crow",
                "crown",
                "crowd",
                "crib",
                "desk",
                "dime",
                "dirt",
                "dress",
                "fang ",
                "field",
                "flag",
                "flower",
                "fog",
                "game",
                "heat",
                "hill",
                "home",
                "horn",
                "hose",
                "joke",
                "juice",
                "kite",
                "lake",
                "maid",
                "mask",
                "mice",
                "milk",
                "mint",
                "meal",
                "meat",
                "moon",
                "mother",
                "morning",
                "name",
                "nest",
                "nose",
                "pear",
                "pen",
                "pencil",
                "plant",
                "rain",
                "river",
                "road",
                "rock",
                "room",
                "rose",
                "seed",
                "shape",
                "shoe",
                "shop",
                "show",
                "sink",
                "snail",
                "snake",
                "snow",
                "soda",
                "sofa",
                "star",
                "step",
                "stew",
                "stove",
                "straw",
                "string",
                "summer",
                "swing",
                "table",
                "tank",
                "team",
                "tent",
                "test",
                "toes",
                "tree",
                "vest",
                "water",
                "wing",
                "winter",
                "woman",
                "women",
                "alarm",
                "animal",
                "aunt",
                "bait",
                "balloon",
                "bath",
                "bead",
                "beam",
                "bean",
                "bedroom",
                "boot",
                "bread",
                "brick",
                "brother",
                "camp",
                "chicken",
                "children",
                "crook",
                "deer",
                "dock",
                "doctor",
                "downtown",
                "drum",
                "dust",
                "eye",
                "family",
                "father",
                "fight",
                "flesh",
                "food",
                "frog",
                "goose",
                "grade",
                "grandfather",
                "grandmother",
                "grape",
                "grass",
                "hook",
                "horse",
                "jail",
                "jam",
                "kiss",
                "kitten",
                "light",
                "loaf",
                "lock",
                "lunch",
                "lunchroom",
                "meal",
                "mother",
                "notebook",
                "owl",
                "pail",
                "parent",
                "park",
                "plot",
                "rabbit",
                "rake",
                "robin",
                "sack",
                "sail",
                "scale",
                "sea",
                "sister",
                "soap",
                "song",
                "spark",
                "space",
                "spoon",
                "spot",
                "spy",
                "summer",
                "tiger",
                "toad",
                "town",
                "trail",
                "tramp",
                "tray",
                "trick",
                "trip",
                "uncle",
                "vase",
                "winter",
                "water",
                "week",
                "wheel",
                "wish",
                "wool",
                "yard",
                "zebra",
                "actor",
                "airplane",
                "airport",
                "army",
                "baseball",
                "beef",
                "birthday",
                "boy",
                "brush",
                "bushes",
                "butter ",
                "cast",
                "cave",
                "cent",
                "cherries",
                "cherry",
                "cobweb",
                "coil",
                "cracker",
                "dinner",
                "eggnog",
                "elbow",
                "face",
                "fireman",
                "flavor",
                "gate",
                "glove",
                "glue",
                "goldfish",
                "goose",
                "grain",
                "hair",
                "haircut",
                "hobbies",
                "holiday",
                "hot",
                "jellyfish",
                "ladybug",
                "mailbox",
                "number",
                "oatmeal",
                "pail",
                "pancake",
                "pear",
                "pest",
                "popcorn",
                "queen",
                "quicksand",
                "quiet",
                "quilt",
                "rainstorm",
                "scarecrow",
                "scarf",
                "stream",
                "street",
                "sugar",
                "throne",
                "toothpaste",
                "twig",
                "volleyball",
                "wood",
                "wrench",
                "advice",
                "anger",
                "answer",
                "apple",
                "arithmetic",
                "badge",
                "basket",
                "basketball",
                "battle",
                "beast",
                "beetle",
                "beggar",
                "brain",
                "branch",
                "bubble",
                "bucket",
                "cactus",
                "cannon",
                "cattle",
                "celery",
                "cellar",
                "cloth",
                "coach",
                "coast",
                "crate",
                "cream",
                "daughter",
                "donkey",
                "drug",
                "earthquake",
                "feast",
                "fifth",
                "finger",
                "flock",
                "frame",
                "furniture",
                "geese",
                "ghost",
                "giraffe",
                "governor",
                "honey",
                "hope",
                "hydrant",
                "icicle",
                "income",
                "island",
                "jeans",
                "judge",
                "lace",
                "lamp",
                "lettuce",
                "marble",
                "month",
                "north",
                "ocean",
                "patch",
                "plane",
                "playground",
                "poison",
                "riddle",
                "rifle",
                "scale",
                "seashore",
                "sheet",
                "sidewalk",
                "skate",
                "slave",
                "sleet",
                "smoke",
                "stage",
                "station",
                "thrill",
                "throat",
                "throne",
                "title",
                "toothbrush",
                "turkey",
                "underwear",
                "vacation",
                "vegetable",
                "visitor",
                "voyage",
                "year",
                "accepts",
                "adds"   ,
                    "admires"    ,
                    "admits" ,
                    "advises"    ,
                    "affords"    ,
                    "agrees" ,
                    "alerts"    ,
                    "allows" ,
                    "backs"  ,
                    "bakes"  ,
                    "balances"   ,
                    "bans"   ,
                    "bangs"  ,
                    "bares"  ,
                    "bats"   ,
                    "bathes" ,
                    "battles"    ,
                    "beams"  ,
                    "calculates"   ,
                    "calls "      ,
                    "camps"  ,
                    "cares"  ,
                    "carrys" ,
                    "carves" ,
                    "causes" ,
                    "challenges" ,
                    "changes"    ,
                    "charges"    ,
                    "chases" ,
                    "cheats" ,
                    "checks" ,
                    "cheers" ,
                    "chews"  ,
                    "dams"   ,
                    "damages"    ,
                    "dances" ,
                    "dares"  ,
                    "decays" ,
                    "deceives"   ,
                    "decides"    ,
                    "decorates"  ,
                    "delays" ,
                    "delights"   ,
                    "earns"  ,
                    "educates"   ,
                    "embarrasss" ,
                    "employs"    ,
                    "emptys" ,
                    "encourages" ,
                    "faces"  ,
                    "fades"  ,
                    "fails"  ,
                    "fancys" ,
                    "fastens"    ,
                    "faxs"   ,
                    "fears"  ,
                    "fences" ,
                    "gathers"    ,
                    "gazes"  ,
                    "glows"  ,
                    "glues"  ,
                    "hammers"    ,
                    "hands"  ,
                    "handles"    ,
                    "hangs"  ,
                    "happens"    ,
                    "harasss"    ,
                    "identifys"  ,
                    "ignores"    ,
                    "imagines"   ,
                    "impresss"   ,
                    "improves"   ,
                    "includes"   ,
                    "jails"  ,
                    "jams"   ,
                    "kicks"  ,
                    "kills"  ,
                    "labels" ,
                    "lands"  ,
                    "lasts"  ,
                    "laughs" ,
                    "launchs"    ,
                    "mans"   ,
                    "manages"    ,
                    "marchs" ,
                    "marks"  ,
                    "marrys" ,
                    "matchs" ,
                    "mates"  ,
                    "nails"  ,
                    "names"  ,
                    "obeys"  ,
                    "objects"    ,
                    "observes"   ,
                    "packs"  ,
                    "paddles"    ,
                    "paints" ,
                    "parks"  ,
                    "parts"  ,
                    "passs"  ,
                    "pastes" ,
                    "pats"   ,
                    "pauses" ,
                    "pecks"  ,
                    "pedals" ,
                    "peels"  ,
                    "peeps"  ,
                    "performs"   ,
                    "permits"    ,
                    "questions"  ,
                    "races"  ,
                    "radiates"   ,
                    "rains"  ,
                    "raises" ,
                    "reachs" ,
                    "realises"   ,
                    "receives"   ,
                    "recognises" ,
                    "records"    ,
                    "reduces"    ,
                    "reflects"   ,
                    "sacks"  ,
                    "sails"  ,
                    "satisfys"   ,
                    "saves"  ,
                    "saws"   ,
                    "scares" ,
                    "scatters"   ,
                    "scolds" ,
                    "scorchs"    ,
                    "scrapes"    ,
                    "scratchs"   ,
                    "screams"    ,
                    "screws" ,
                    "scribbles"  ,
                    "scrubs" ,
                    "seals"  ,
                    "searchs"    ,
                    "separates"  ,
                    "serves" ,
                    "settles"    ,
                    "shades" ,
                    "shares" ,
                    "shaves" ,
                    "shelters"   ,
                    "talks"  ,
                    "tames"  ,
                    "taps"   ,
                    "tastes" ,
                    "teases" ,
                    "telephones" ,
                    "tempts" ,
                    "terrifys"   ,
                    "tests"  ,
                    "thanks" ,
                    "undresss"   ,
                    "unfastens"  ,
                    "vanishs"    ,
                    "wails"  ,
                    "waits"  ,
                    "walks"  ,
                    "wanders"    ,
                    "wants"  ,
                    "warms"  ,
                    "warns"  ,
                    "washs"  ,
                    "x-rays" ,
                    "yawns"  ,
                    "zips"   ,
                    "amuses" ,
                    "analyses"   ,
                    "analyzes"   ,
                    "announces"  ,
                    "annoys" ,
                    "answers"    ,
                    "apologises" ,
                    "appears"    ,
                    "begs"   ,
                    "behaves"    ,
                    "belongs"    ,
                    "bleachs"    ,
                    "blesss" ,
                    "blinds" ,
                    "blinks" ,
                    "blots"  ,
                    "blushs" ,
                    "boasts" ,
                    "chokes" ,
                    "chops"  ,
                    "claims" ,
                    "claps"  ,
                    "cleans" ,
                    "clears" ,
                    "clips"  ,
                    "closes" ,
                    "coachs" ,
                    "coils"  ,
                    "collects"   ,
                    "colours"    ,
                    "combs"  ,
                    "commands"   ,
                    "communicates"   ,
                    "delivers"   ,
                    "depends"    ,
                    "describes"  ,
                    "deserts"    ,
                    "deserves"   ,
                    "destroys"   ,
                    "detects"    ,
                    "develops"   ,
                    "disagrees"  ,
                    "disappears" ,
                    "ends"   ,
                    "enjoys" ,
                    "enters" ,
                    "entertains" ,
                    "escapes"    ,
                    "examines"   ,
                    "fetchs" ,
                    "files"  ,
                    "fills"  ,
                    "films"  ,
                    "fires"  ,
                    "fits"   ,
                    "fixs"   ,
                    "flaps"  ,
                    "grabs"  ,
                    "grates" ,
                    "greases"    ,
                    "greets" ,
                    "harms"  ,
                    "hates"  ,
                    "haunts" ,
                    "heads"  ,
                    "heals"  ,
                    "heaps"  ,
                    "increases"  ,
                    "influences" ,
                    "informs"    ,
                    "injects"    ,
                    "injures"    ,
                    "instructs"  ,
                    "jogs"   ,
                    "joins"  ,
                    "kisss"  ,
                    "kneels" ,
                    "learns" ,
                    "levels" ,
                    "licenses"   ,
                    "licks"  ,
                    "lies"   ,
                    "matters"    ,
                    "measures"   ,
                    "meddles"    ,
                    "melts"  ,
                    "memorises"  ,
                    "mends"  ,
                    "mess ups"   ,
                    "needs"  ,
                    "nests"  ,
                    "obtains"    ,
                    "occurs",
                    "offends",
                    "phones" ,
                    "picks"  ,
                    "pinchs" ,
                    "pines"  ,
                    "places" ,
                    "plans"  ,
                    "plants" ,
                    "plays"  ,
                    "pleases"    ,
                    "plugs"  ,
                    "points" ,
                    "pokes"  ,
                    "polishs"    ,
                    "pops"   ,
                    "queues" ,
                    "refuses"    ,
                    "regrets"    ,
                    "reigns" ,
                    "rejects"    ,
                    "rejoices"   ,
                    "relaxs" ,
                    "releases"   ,
                    "relys"  ,
                    "remains"    ,
                    "remembers"  ,
                    "reminds"    ,
                    "shivers"    ,
                    "shocks" ,
                    "shops"  ,
                    "shrugs" ,
                    "sighs"  ,
                    "signs"  ,
                    "signals"    ,
                    "sins"   ,
                    "sips"   ,
                    "skis"   ,
                    "skips"  ,
                    "slaps"  ,
                    "slips"  ,
                    "slows"  ,
                    "smashs" ,
                    "smells" ,
                    "smiles" ,
                    "smokes" ,
                    "snatchs"    ,
                    "sneezes"    ,
                    "sniffs" ,
                    "snores" ,
                    "snows"  ,
                    "soaks"  ,
                    "thaws"  ,
                    "ticks"  ,
                    "tickles"    ,
                    "ties"   ,
                    "times"  ,
                    "tips"   ,
                    "tires"  ,
                    "touchs" ,
                    "tours"  ,
                    "tows"   ,
                    "unites" ,
                    "unlocks"    ,
                    "visits" ,
                    "wastes" ,
                    "watchs" ,
                    "waters" ,
                    "waves"  ,
                    "weighs" ,
                    "welcomes"   ,
                    "whines" ,
                    "whips"  ,
                    "yells"  ,
                    "zooms"  ,
                    "applauds"   ,
                    "appreciates"    ,
                    "approves"   ,
                    "argues" ,
                    "arranges"   ,
                    "arrests"    ,
                    "arrives"    ,
                    "asks"   ,
                    "boils"  ,
                    "bolts"  ,
                    "bombs"  ,
                    "books"  ,
                    "bores"  ,
                    "borrows"    ,
                    "bounces"    ,
                    "bows"   ,
                    "boxs"   ,
                    "brakes" ,
                    "compares"   ,
                    "competes"   ,
                    "complains"  ,
                    "completes"  ,
                    "concentrates"   ,
                    "concerns"   ,
                    "confesss"   ,
                    "confuses"   ,
                    "connects"   ,
                    "considers"  ,
                    "consists"   ,
                    "contains"   ,
                    "continues"  ,
                    "copys"  ,
                    "corrects"   ,
                    "disapproves"    ,
                    "disarms"    ,
                    "discovers"  ,
                    "dislikes"   ,
                    "divides"    ,
                    "doubles"    ,
                    "doubts" ,
                    "drags"  ,
                    "drains" ,
                    "dreams" ,
                    "excites"    ,
                    "excuses"    ,
                    "exercises"  ,
                    "exists" ,
                    "expands"    ,
                    "expects"    ,
                    "flashs" ,
                    "floats" ,
                    "floods" ,
                    "flows"  ,
                    "flowers"    ,
                    "folds"  ,
                    "follows"    ,
                    "fools"  ,
                    "grins"  ,
                    "grips"  ,
                    "groans" ,
                    "guarantees" ,
                    "heats"  ,
                    "helps"  ,
                    "hooks"  ,
                    "hops"   ,
                    "hopes"  ,
                    "hovers" ,
                    "intends"    ,
                    "interests"  ,
                    "interferes" ,
                    "interrupts" ,
                    "introduces" ,
                    "invents"    ,
                    "jokes"  ,
                    "judges" ,
                    "knits"  ,
                    "knocks" ,
                    "lightens"   ,
                    "likes"  ,
                    "lists"  ,
                    "listens"    ,
                    "lives"  ,
                    "milks"  ,
                    "mines"  ,
                    "misss"  ,
                    "mixs"   ,
                    "moans"  ,
                    "moors"  ,
                    "mourns" ,
                    "nods"   ,
                    "notes"  ,
                    "offers" ,
                    "opens"  ,
                    "orders" ,
                    "possesss"   ,
                    "posts"  ,
                    "pours"  ,
                    "practise s" ,
                    "practice s" ,
                    "prays"  ,
                    "preachs"    ,
                    "precedes"   ,
                    "prefers"    ,
                    "prepares"   ,
                    "presents"   ,
                    "preserves"  ,
                    "presss" ,
                    "pretends"   ,
                    "removes"    ,
                    "repairs"    ,
                    "repeats"    ,
                    "replaces"   ,
                    "replys" ,
                    "reports"    ,
                    "reproduces" ,
                    "requests"   ,
                    "rescues"    ,
                    "retires"    ,
                    "returns"    ,
                    "soothes"    ,
                    "sounds" ,
                    "spares" ,
                    "sparks" ,
                    "sparkles"   ,
                    "spells" ,
                    "spills" ,
                    "spoils" ,
                    "spots"  ,
                    "sprays" ,
                    "sprouts"    ,
                    "squashs"    ,
                    "squeaks"    ,
                    "squeals"    ,
                    "squeezes"   ,
                    "stains" ,
                    "stamps" ,
                    "stares" ,
                    "starts" ,
                    "stays"  ,
                    "steers" ,
                    "steps"  ,
                    "stirs"  ,
                    "stitchs"    ,
                    "traces" ,
                    "trades" ,
                    "trains" ,
                    "transports" ,
                    "traps"  ,
                    "travels"    ,
                    "treats" ,
                    "trembles"   ,
                    "tricks" ,
                    "trips"  ,
                    "unpacks"    ,
                    "untidys"    ,
                    "whirls" ,
                    "whispers"   ,
                    "whistles"   ,
                    "winks"  ,
                    "wipes"  ,
                    "wishs"  ,
                    "wobbles"    ,
                    "wonders"    ,
                    "attachs"    ,
                    "attacks"    ,
                    "attempts"   ,
                    "attends"    ,
                    "attracts"   ,
                    "avoids" ,
                    "branchs"    ,
                    "breathes"   ,
                    "bruises"    ,
                    "brushs" ,
                    "bubbles"    ,
                    "bumps"  ,
                    "burns"  ,
                    "burys"  ,
                    "buzzs"  ,
                    "coughs" ,
                    "counts" ,
                    "covers" ,
                    "cracks" ,
                    "crashs" ,
                    "crawls" ,
                    "crosss" ,
                    "crushs" ,
                    "crys"   ,
                    "cures"  ,
                    "curls"  ,
                    "curves" ,
                    "cycles" ,
                    "dresss" ,
                    "drips"  ,
                    "drops"  ,
                    "drowns" ,
                    "drums"  ,
                    "drys"   ,
                    "dusts"  ,
                    "explains"   ,
                    "explodes"   ,
                    "extends"    ,
                    "forces" ,
                    "forms"  ,
                    "founds" ,
                    "frames" ,
                    "frightens"  ,
                    "frys"   ,
                    "guards" ,
                    "guesss" ,
                    "guides" ,
                    "hugs"   ,
                    "hums"   ,
                    "hunts"  ,
                    "hurrys" ,
                    "invites"    ,
                    "irritates"  ,
                    "itchs"  ,
                    "juggles"    ,
                    "jumps"  ,
                    "knots"  ,
                    "loads"  ,
                    "locks"  ,
                    "longs"  ,
                    "looks"  ,
                    "loves"  ,
                    "moves"  ,
                    "muddles"    ,
                    "mugs"   ,
                    "multiplys"  ,
                    "murders",
                    "notices",
                    "numbers"    ,
                    "overflows"  ,
                    "owes"   ,
                    "owns"   ,
                    "prevents"   ,
                    "pricks" ,
                    "prints" ,
                    "produces"   ,
                    "programs"   ,
                    "promises"   ,
                    "protects"   ,
                    "provides"   ,
                    "pulls"  ,
                    "pumps"  ,
                    "punchs" ,
                    "punctures"  ,
                    "punishs"    ,
                    "pushs"  ,
                    "rhymes" ,
                    "rinses" ,
                    "risks"  ,
                    "robs"   ,
                    "rocks"  ,
                    "rolls"  ,
                    "rots"   ,
                    "rubs"   ,
                    "ruins"  ,
                    "rules"  ,
                    "rushs"  ,
                    "stops"  ,
                    "stores" ,
                    "straps" ,
                    "strengthens"    ,
                    "stretchs"   ,
                    "strips" ,
                    "strokes"    ,
                    "stuffs" ,
                    "subtracts"  ,
                    "succeeds"   ,
                    "sucks"  ,
                    "suffers"    ,
                    "suggests"   ,
                    "suits"  ,
                    "supplys"    ,
                    "supports"   ,
                    "supposes"   ,
                    "surprises"  ,
                    "surrounds"  ,
                    "suspects"   ,
                    "suspends"   ,
                    "switchs"    ,
                    "trots"  ,
                    "troubles"   ,
                    "trusts" ,
                    "trys"   ,
                    "tugs"   ,
                    "tumbles"    ,
                    "turns"  ,
                    "twists" ,
                    "types"  ,
                    "uses"   ,
                    "works"  ,
                    "worrys" ,
                    "wraps"  ,
                    "wrecks" ,
                    "wrestles"   ,
                    "wriggles"

                };
        public string chooseWord()
        {
            Random rnd = new Random();
            return words[rnd.Next(1003)];
        }

    }
}
